### ISSUE TITLE
GetMats_f8 calls ReadFASTLinear

### ISSUE THREAD

**Issue by hassan-shehawy** [NWTC/MBC#1]
hi
ReadFASTLinear function is called inside GetMats_f8 but you removed it, is there a reason for that? Because it won't work without it

**Comment by jjonkman** [comment]
The ReadFASTLinear MATLAB script is contained in the MATLAB Toolbox, so, there was no reason to duplicate it here.

Is there a reason you are using MBC from the old-NWTC organization?  The newest MBC and MATLAB Toolbox code is available on the OpenFAST organization: https://github.com/OpenFAST/matlab-toolbox.  In this organization, we've merged MBC into the MATLAB Toolbox to avoid any confusion and file duplication.

**Comment by hassan-shehawy** [comment]
Thanks for clarification. Just to double check, this function (ReadFASTLinear) can read .lin file from OpenFAST? 

No, I was looking for the MBC tool on the NREL website and on this page: https://nwtc.nrel.gov/MBC it links to here for MBC for FAST 8

**Comment by jjonkman** [comment]
The function ReadFASTLinear from the OpenFAST organization (https://github.com/OpenFAST/matlab-toolbox/blob/master/Utilities/ReadFASTLinear.m) can read .lin files generated by OpenFAST.

Thanks for reporting the problem with the NWTC Information portal.  I've now changed that page to point to the OpenFAST organization.

**Comment by hassan-shehawy** [comment]
Thanks
